apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: servers
  name: http3onlychained
spec:
  loadBalancerIP: 20.3.166.28
  type: LoadBalancer
  ports:
  - port: 5004
    protocol: UDP
  selector:
    app: grpchttp3